"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Field } from "./auth-shell";
import { useAuth } from "@/hooks/useAuth";

export function SignupForm() {
  const router = useRouter(); const { signup } = useAuth(); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const password = String(form.get("password")); if (password !== form.get("confirmPassword")) { setError("Passwords do not match."); return; } setBusy(true); try { await signup({ name: String(form.get("name")), email: String(form.get("email")), password }); router.push("/dashboard?role=staff"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create your account."); } finally { setBusy(false); } }
  return <div className="w-full"><h1 className="text-[2rem] font-semibold tracking-[-.035em] text-[#17251e]">Create your staff account</h1><p className="mt-2 text-sm leading-6 text-[#758078]">Join the Al Madel workspace. Administrator accounts are created directly by the system.</p><div className="mt-6 flex items-center gap-3 rounded-xl border border-[#d8e5dc] bg-[#edf5f0] px-4 py-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#1d4934] text-sm font-bold text-white">S</span><div><p className="text-sm font-semibold text-[#234433]">Staff registration</p><p className="text-xs text-[#63766a]">Your account will be assigned the staff role.</p></div></div>
    <form className="mt-6 space-y-4" onSubmit={submit}><Field label="Full name" name="name" placeholder="Your full name" autoComplete="name" minLength={2} required /><Field label="Email address" name="email" type="email" placeholder="you@almadel.com" autoComplete="email" required /><Field label="Password" name="password" type={show ? "text" : "password"} placeholder="At least 8 characters" autoComplete="new-password" minLength={8} required right={<button className="absolute inset-y-0 right-0 px-4 text-xs font-semibold text-[#617068]" type="button" onClick={() => setShow(!show)}>{show ? "Hide" : "Show"}</button>} /><Field label="Confirm password" name="confirmPassword" type={show ? "text" : "password"} placeholder="Repeat your password" autoComplete="new-password" minLength={8} required />
      <label className="flex items-start gap-2.5 text-xs leading-5 text-[#67736c]"><input className="mt-1 accent-[#1d4934]" type="checkbox" required /><span>I agree to the Terms of Service and Privacy Policy.</span></label>{error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="h-12 w-full rounded-xl bg-[#1d4934] font-semibold text-white shadow-[0_8px_20px_rgba(29,73,52,.18)] transition hover:bg-[#153b29] disabled:opacity-60">{busy ? "Creating account…" : "Create staff account"}</button></form></div>;
}
